### ISSUE TITLE
How to run, debug and deploy Rosetta

### ISSUE THREAD

**Issue by giulioverazzo** [Unidata/rosetta#168]
Hi and thanks for making Rosetta!

I've cloned the project and I'm trying to run it in a local environment.
I'm using Ubuntu 18.04 on WSL and i've installed openjdk-8-jdk.

As far as I understand, I need to run `./gradlew` and then `./gradlew tomcatRun`. Using this last command I got a lot deprecated functions warnings and this exception:

`Exception in thread "Thread-381" org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 143
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:42)
        at org.gradle.process.internal.DefaultExecActionFactory.javaexec(DefaultExecActionFactory.java:168)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1156)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1151)
        at org.gradle.api.Project$javaexec$8.call(Unknown Source)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure3.doCall(LauncherBase.groovy:197)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure3.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.lang.Thread.run(Thread.java:748)`

however the Tomcat server starts and I can see the Rosetta homepage at http://localhost:8888/rosetta

On the homepage I click "Single station timeseries" and then I choose the csv file to load. At this point I got this new exception:

`SEVERE: Servlet.service() for servlet [rosetta] in context with path [/rosetta] threw exception [An exception occurred processing [/WEB-INF/views/jspf/customFileTypeAttributes.jspf] at line [8]

5: <p>Please tell us which lines in your data file are header lines:</p>
6: <label for="noHeaderLines" class="noHeaderLines">
7:     <input type="checkbox" name="noHeaderLines"
8:            <c:if test="${data.noHeaderLines eq 'true'}">checked</c:if> value="${data.noHeaderLines}"
9:            id="noHeaderLines"/>
10:     No header lines available in this file
11: </label>

Stacktrace:] with root cause
javax.el.PropertyNotFoundException: Property [noHeaderLines] not readable on type [edu.ucar.unidata.rosetta.domain.wizard.WizardData]
        at javax.el.BeanELResolver$BeanProperty.read(BeanELResolver.java:307)
        at javax.el.BeanELResolver$BeanProperty.access$000(BeanELResolver.java:265)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:86)
        at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:125)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
        at org.apache.el.parser.AstEqual.getValue(AstEqual.java:37)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
        at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:699)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_c_005fif_005f28(wizard_jsp.java:4470)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_c_005fwhen_005f12(wizard_jsp.java:4318)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_c_005fchoose_005f2(wizard_jsp.java:1449)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_form_005fform_005f0(wizard_jsp.java:1132)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_c_005fwhen_005f1(wizard_jsp.java:1032)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspx_meth_c_005fchoose_005f1(wizard_jsp.java:991)
        at org.apache.jsp.WEB_002dINF.views.wizard_jsp._jspService(wizard_jsp.java:462)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:378)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:326)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:171)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)`

I assume that I'm missing something in the build phase or I'm doing something wrong. My ultimate goal is to create a Dockerized version of Rosetta with a bit a UI personalization. Can you please provide me with instruction on how to prepare the correct environment to make rosetta work and to debug it? (I use visual studio code).

Thank you so much!

**Comment by oxelson** [comment]
Hi @giulioverazzo, thanks for reporting this.  It is indeed a bug and not something you did.  I'll get a fix up for you next week (along with some enhancements).  
Please let me know if you have any questions!

**Comment by xiaocui123** [comment]
> 

have you resolve this problem?and how?thanks!

**Comment by oxelson** [comment]
Hi @xiaocui123 - we are in a holding pattern with Rosetta while we retool the THREDDS project (which Rosetta is a part of).  Because of this, Rosetta support and development have been placed on the back burner for a bit.  Hoping to resume this project in the fall.  I will keep you posted on the progress.
